Skip to content
DEV Community
Search...

Log in
Create account

0
Jump to Comments
4
Save

Cover image for Como adicionar o Snake Game (jogo da cobrinha) no seu perfil do Github 🐍
Henrique Lopes
Henrique Lopes
Posted on 4 de jan. de 2022


6

3
Como adicionar o Snake Game (jogo da cobrinha) no seu perfil do Github 🐍
#
github
Primeiramente devo deixar claro que esse artigo foi desenvolvido com base em vários outros artigos e reconstruído para deixar o mais claro possível a forma para inserir o Snake Game em seu perfil.

Funcionamento. "Contributions in the last year":
Basicamente o Snake game funciona realizando uma coleta da sua tabela de contribuições no Github. ele faz a renderização dessas informações e gera dois arquivos, um em formato gif e outro em svg. São esses arquivos que iremos utilizar para inserir a animação no perfil do Github.

Repositorio do projeto a ser utilizado: Platane/snk

Exemple

Requisito. "Repositório base":
Para que você possa prosseguir é necessário que você tenha o repositório do perfil (repositório com o mesmo nome de usuário), porém para gerar os arquivos também funciona em outro repositório.

Actions. "Configuração inicial":
Inicialmente é necessário que você acesse o seu repositório escolhido e vá em Settings.

Configuração inicial

No menu vertical ao lado esquerdo selecione o menu Actions e em seguida ative a permissão “Allow all actions”. Também é possível selecionar diretamente o repositório.

Ative a permissão

Actions. "Criando Gerador":
Agora que temos o repositório configurado iremos adicionar o "script" para gerar dos arquivos. No repositório, vá em Actions.

Criando o gerador

Em seguida vamos utilizar “Simple workflow” apenas com o mínimo necessário para rodar o codigo.

Configurando

Agora é apenas alterar o nome do arquivo e colar o código da configuração com o seu usuário.

Alterar jnome do arquivo

alterando o username
# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
      # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que será utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: eduardzs #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Retornando na opção Actions do repositório, clique em “Run workflow”:

Repositorio

Pasta dos arquivos:
Em seu repositorio cliente em main e selecione a branch output:
output

E aqui estão os arquivos gerados que você pode utilizar como bem entender:

Arquivos

Codigo Github para utilização:

![snake gif](https://github.com/SEU_USUARIO/SEU_REPOSITORIO/blob/output/github-contribution-grid-snake.svg)

Top comments (0)

Subscribe
pic
Add to the discussion
Code of Conduct • Report abuse
DEV Community

DEV Author Spotlight
bekahhw image 
BekahHW
Hey! I'm Bekah. I'm a career-changer. Bootcamp grad. Dev. Writer. Keynote Speaker. Mom to 4 kids. Creator, Maintainer, Podcast co-host: VirtualCoffee.io | Developer Experience Lead, @OpenSauced
Meet BekahHW, a dynamic developer, writer, and keynote speaker based in Ohio. They're a bootcamp grad turned Developer Experience Lead at OpenSauced, and co-host of the VirtualCoffee.io podcast. They're also a supermom to four kids, juggling a thriving tech career and family life with apparent ease.

BekahHW's articles are a treasure trove of insights into the world of open-source software (OSS). They've been running an engaging series called #100DaysOfOSS, where they delve into OSS terms from A to Z. From explaining concepts like 'Collaboration', 'Bug', and 'Android' to sharing their thoughts on these topics, they've got you covered.

They also provide valuable guidance on navigating the challenges of OSS contributions, such as keeping your branch up to date and handling merge conflicts. Moreover, they're a strong advocate for building in public and regularly encourage their readers to share their progress on projects. If you're looking to dive into the OSS world or enhance your existing knowledge, you'll want to hit that 'follow' button for BekahHW.

OpenSauced 
Open Source ABCs: Collaboration
BekahHW for OpenSauced ・ Aug 1
#opensource #discuss #100daysofoss
OpenSauced 
Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews
BekahHW for OpenSauced ・ Jul 31
#opensource #github #beginners #git
bekahhw 
Build in Public: Final Check-in
BekahHW ・ Jul 30
#beginners #learning #discuss
OpenSauced 
Who's looking for open source contributors? (week 52)
BekahHW for OpenSauced ・ Jul 28
#discuss #opensource #contributorswanted #codenewbie
OpenSauced 
Open Source ABCs: Bug
BekahHW for OpenSauced ・ Jul 27
#opensource #discuss #100daysofoss
OpenSauced 
Open Source ABCs: Android
BekahHW for OpenSauced ・ Jul 25
#opensource #discuss #100daysofoss
OpenSauced 
Setting Goals for Your Open Source Contributions
BekahHW for OpenSauced ・ Jul 24
#opensource #codenewbie #beginners #challenge
OpenSauced 
Who's looking for open source contributors? (week 51)
BekahHW for OpenSauced ・ Jul 21
#discuss #opensource #contributorswanted #codenewbie
Read next
og_dev profile image
Leveraging OpenSauced AI to Generate Compelling PR Descriptions
OGBONNA SUNDAY - Jun 7

mrizwanashiq profile image
Monorepo vs Microrepo
Muhammad Rizwan Ashiq - Jun 8

danstano profile image
How to Create and update your Github Personal Token Issue
Danstan-O - May 5

lorendsr profile image
Sync GitHub Repos to Notion
Loren 🤓 - Jun 7


Henrique Lopes
Follow
"Não há razão alguma em usar a palavra “impossível” para descrever algo que claramente pode acontecer."
JOINED
5 de set. de 2021
Trending on DEV Community 
Sloan the DEV Moderator profile image
Code Talk: Which Languages Speak to Your Developer Soul?
#codenewbie #beginners #discuss #career
dev.to staff profile image
It's Follow Friday! Who's Lighting up Your dev.to World? ✨💫
#discuss #followfriday
Ben Halpern profile image
Meme Monday
#discuss #watercooler #jokes
DEV Community

🌚 Life is too short to browse without dark mode
You can customize your theme, font, and more when you are signed in.

# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
      # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que será utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: nomeUsuario #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
DEV Community — A constructive and inclusive social network for software developers. With you every step of your journey.

Home
Listings
Podcasts
Videos
Tags
FAQ
Forem Shop
Advertise on DEV
About
Contact
Guides
Software comparisons
Code of Conduct
Privacy Policy
Terms of use
Built on Forem — the open source software that powers DEV and other inclusive communities.

Made with love and Ruby on Rails. DEV Community © 2016 - 2023.
